# Generated by Django 4.0 on 2022-01-20 12:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('brandName', models.CharField(max_length=50, unique=True)),
                ('brandImage', models.ImageField(upload_to='Brand/images')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('category_id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category_name', models.CharField(max_length=500, unique=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='Product.category')),
            ],
        ),
        migrations.CreateModel(
            name='Collections',
            fields=[
                ('collection_id', models.AutoField(primary_key=True, serialize=False)),
                ('collection_title', models.CharField(max_length=500, unique=True)),
                ('collection_desc', models.CharField(max_length=500)),
                ('collection_image', models.ImageField(upload_to='Collections/images')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('gender', models.CharField(choices=[('ME', 'Men'), ('WO', 'Women'), ('KI', 'Kid')], default='ME', max_length=2)),
                ('product_title', models.CharField(max_length=50)),
                ('product_description', models.CharField(max_length=350, null=True)),
                ('product_price', models.DecimalField(decimal_places=2, max_digits=20)),
                ('discount_type', models.CharField(choices=[('PE', 'PERCENTAGE'), ('FI', 'FIXED')], default='PE', max_length=2)),
                ('product_discount', models.IntegerField(default=0, max_length=100)),
                ('product_size', models.JSONField(null=True)),
                ('product_material', models.CharField(choices=[('NO', 'NONE'), ('CO', 'COTTON'), ('JE', 'JEANS'), ('LE', 'LEATHER'), ('SA', 'SATIN')], default='NO', max_length=2)),
                ('product_occasion', models.CharField(choices=[('CA', 'CASUAL'), ('SP', 'SPORT'), ('TR', 'TREND'), ('WO', 'WORK'), ('EV', 'EVENT'), ('NU', 'NURSING'), ('PA', 'PARTY')], default='CA', max_length=2)),
                ('product_color', models.JSONField(default=list)),
                ('brandName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Product.brand')),
                ('product_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Product.category')),
            ],
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('sizeID', models.AutoField(primary_key=True, serialize=False)),
                ('size', models.CharField(max_length=50, unique=True)),
                ('size_name', models.CharField(max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(choices=[('0', 'RED'), ('1', 'YELLOW'), ('2', 'GREEN'), ('3', 'BLUE'), ('4', 'Orange'), ('5', 'Beige'), ('6', 'Black'), ('7', 'Blue-Green'), ('8', 'Burgundy'), ('9', 'Gold'), ('10', 'Silver'), ('11', 'MultiColor'), ('12', 'White')], max_length=2)),
                ('quantity', models.IntegerField(max_length=500)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Product.product')),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Product.size')),
            ],
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('product_imageID', models.AutoField(primary_key=True, serialize=False)),
                ('product_image', models.ImageField(upload_to='products')),
                ('product_color', models.CharField(max_length=2)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Product.product')),
            ],
        ),
        migrations.CreateModel(
            name='CollectionsVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.JSONField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Product.collections')),
            ],
        ),
    ]
