# Generated by Django 4.0 on 2022-01-19 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0006_alter_product_product_color_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_color',
            field=models.JSONField(choices=[('0', 'RED'), ('1', 'YELLOW'), ('2', 'GREEN'), ('3', 'BLUE'), ('4', 'Orange'), ('5', 'Beige'), ('6', 'Black'), ('7', 'Blue-Green'), ('8', 'Burgundy'), ('9', 'Gold'), ('10', 'Silver'), ('11', 'MultiColor'), ('12', 'White')], default=list),
        ),
    ]
