# Generated by Django 4.0 on 2022-01-14 12:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('brandName', models.CharField(max_length=50, unique=True)),
                ('brandImage', models.ImageField(upload_to='Brand/images')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('category_id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category_name', models.CharField(max_length=500, unique=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='Seller.category')),
            ],
        ),
        migrations.CreateModel(
            name='Collections',
            fields=[
                ('collection_id', models.AutoField(primary_key=True, serialize=False)),
                ('collection_title', models.CharField(max_length=500, unique=True)),
                ('collection_desc', models.CharField(max_length=500)),
                ('collection_image', models.ImageField(upload_to='Collections/images')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('color_id', models.AutoField(primary_key=True, serialize=False)),
                ('color_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('gender', models.CharField(choices=[('ME', 'Men'), ('WO', 'Women'), ('KI', 'Kid')], default='ME', max_length=2)),
                ('product_title', models.CharField(max_length=50)),
                ('product_description', models.CharField(max_length=350, null=True)),
                ('product_price', models.DecimalField(decimal_places=2, max_digits=20)),
                ('product_discount', models.IntegerField(default=0, max_length=100)),
                ('product_size', models.JSONField(null=True)),
                ('product_image1', models.ImageField(null=True, upload_to='Product/images')),
                ('product_image2', models.ImageField(null=True, upload_to='Product/images')),
                ('product_image3', models.ImageField(null=True, upload_to='Product/images')),
                ('product_image4', models.ImageField(null=True, upload_to='Product/images')),
                ('product_image5', models.ImageField(null=True, upload_to='Product/images')),
                ('product_imageList', models.JSONField(null=True)),
                ('brandName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Seller.brand')),
                ('product_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Seller.category')),
                ('product_color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Seller.color')),
            ],
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('sizeID', models.AutoField(primary_key=True, serialize=False)),
                ('size', models.CharField(max_length=50, unique=True)),
                ('size_name', models.CharField(max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(max_length=500)),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Seller.color')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Seller.product')),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Seller.size')),
            ],
        ),
        migrations.CreateModel(
            name='ProductCollections',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.JSONField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Seller.collections')),
            ],
        ),
    ]
