# Generated by Django 4.0 on 2022-01-14 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Seller', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductCollections',
            new_name='CollectionsVariant',
        ),
    ]
