# Generated by Django 4.0 on 2022-01-16 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Seller', '0002_rename_productcollections_collectionsvariant'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShippingCountries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('country_name', models.CharField(max_length=50)),
                ('shipping_cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=50)),
            ],
        ),
    ]
